version: '3.8'
services:
  django_gunicorn: 
    build:
      context: .
    # env_file:
    #   - .env
    volumes:
      - ./static:/static
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - "443:80"
    depends_on:
      - django_gunicorn
  health:
    build: ./Health
    env_file:
      - .env
    ports:
      - "8080:8080"

