# Generated by Django 3.2 on 2022-08-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='MembersNew',
        ),
    ]
